### PR TITLE
add receipt_email to stripe create charge calls

### PR DESCRIPTION
**Pull request by mnelson4**
## Problem this Pull Request solves

Part of https://github.com/eventespresso/eea-stripe-gateway/issues/4#issuecomment-412166065, where @joshfeck pointed out we're not passing the receipt_email.

## How has this been tested

* [ ] Make a payment with Stripe. In the payments logs for that transaction, the `receipt_email` shouldn't be blank (although I'm not sure where the receipt email should appear in Stripe or how they use it.)

## Checklist

* [x] I have read the documentation relating to systems affected by this pull request, see https://github.com/eventespresso/event-espresso-core/tree/master/docs
* [x] User input is adequately validated and sanitized
* [x] all publicly displayed strings are internationalized (usually using `esc_html__()`, see https://codex.wordpress.org/I18n_for_WordPress_Developers)
* [x] My code is tested.
* [x] My code follows the Event Espresso code style.
* [x] My code has proper inline documentation.

### CODE REVIEW

**Comment by mnelson4** [comment]
oups forgot to assign a reviewer

**Comment by mnelson4** [comment]
passing to @joshfeck for testing (see my initial comment for testing notes, although admittedly there isn't much there, hoping you'd have a better idea)

**Comment by sethshoultes** [comment]
@garthkoyle I usually just remove the Stale tag. I'm thinking we might want to stop using the stale tags and stop automatically closing issues.

**Comment by mnelson4** [comment]
fyi @sethshoultes I'm not sure if you saw: http://p2.eventespresso.com/2018/06/26/stale-bot-automatically-closing-our-github-tickets/
Although if we wanted to discuss it, we should probably create a new topic and just reference that old one

**Comment by joshfeck** [comment]
This is ready to be merged.

**Pull request merged**
